databases:
  - name: django_tailwind_app_db
    plan: free
    databaseName: django_tailwind_app_db
    user: lizwi

services:
  - type: web
    plan: free
    name: django_tailwind_app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_tailwind_app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_tailwind_app_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
